
services:

  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRESS_DB: ${DB_NAME}
      POSTGRESS_USERNAME: ${DB_USERNAME}
      POSTGRESS_HOST: ${DB_HOST}
    container_name: postgresDB
    volumes:
      # - /postgres:/var/lib/postgresql/data
        - ./postgres-data:/var/lib/postgresql/data


  # tesloshop:
  #   image: tesloshop
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
